### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by Christelle-12** [Innocent259/My-portfolio#15]
Hello,
Great job so far 👏, kindly check your nav links they have to direct the user to their corresponding pages once clicked.

**Comment by faisalakb** [comment]
Your design and flow are fantastic.  Please check the button contrast ratio.

**Comment by Innocent259** [comment]
Hi @Christelle-12 
Thank you suggestion, I will work on it

**Comment by Innocent259** [comment]
@faisalakb
Yeah I will check on it

**Comment by omer-creator** [comment]
Hey, Your project is god to go. Congrats
