### ISSUE TITLE
Peer to peer review

### ISSUE THREAD

**Issue by helina42** [Innocent259/My-portfolio#7]
Please consider adjusting your margin and padding so that your alignment is similar to the figma templet.

**Comment by Bellagirl-maker** [comment]
Please remove the hamburger  icon from the desktop view

**Comment by AFakhriddinov** [comment]
Please consider your font-sizing for headings and texts to align it with figma template

**Comment by Innocent259** [comment]
@helina42 @AFakhriddinov @Bellagirl-maker Thank you,  all your suggestions are noted!
